[app]
address = "0.0.0.0:6000" # Address of the HTTP Server.
server_timeout = "60s" # Server timeout for HTTP requests.
enable_request_logs = true # Whether to log incoming HTTP requests or not.
log = "info" # Use `debug` to enable verbose logging. Can be set to `info` otherwise.

[providers.prod_alerts]
type = "google_chat" # Type of provider. Currently supported value is `google_chat`.
endpoint = "https://chat.googleapis.com/v1/spaces/AAAAbsDTGv4/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=cfNyCdIlnt1qi56G2498VHiGAz4s8yaqEIVZUK8-SIc%3D"
max_idle_conns =  50 # Max idle connections in the HTTP Client.
timeout = "30s" # Timeout for making requests to Provider.
# proxy_url = "http://internal-squid-proxy.com:3128" # Specify `proxy_url` as your proxy endpoint to route all HTTP requests to the provider via a proxy.
template = "static/message.tmpl" # Path to specify the message template path.
thread_ttl = "12h" # Timeout to keep active alerts in memory. Once this TTL expires, a new thread will be created.
dry_run = false

[providers.dev_alerts]
type = "google_chat"
endpoint = "https://chat.googleapis.com/v1/spaces/AAAAbsDTGv4/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=cfNyCdIlnt1qi56G2498VHiGAz4s8yaqEIVZUK8-SIc%3D"
max_idle_conns =  50
timeout = "30s"
# proxy_url = "http://internal-squid-proxy.com:3128"
template = "static/message.tmpl"
thread_ttl = "12h"
dry_run = false


