server:
  http_listen_port: 9080
  grpc_listen_port: 9095

positions:
  filename: /opt/promtail/positions.yaml

clients:
  - url: http://${STACK_SERVICE_HOSTNAME_LOKI}:3100/loki/api/v1/push

scrape_configs:

- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

  # --log-opt tag="{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
  pipeline_stages:

  - json:
      expressions:
        stream: stream
        attrs: attrs
        tag: attrs.tag

  - regex:
      expression: (?P<ambiente>(?:[^|]*[^|])).(?P<produto>(?:[^|]*[^|])).(?P<cliente>(?:[^|]*[^|])).(?P<servico>(?:[^|]*[^|])).(?P<versao>(?:[^|]*[^|]))
      source: "tag"

  - labels:
      tag:
      ambiente:
      produto:
      cliente:
      servico:
      versao: