FROM ${STACK_SERVICE_IMAGE_MYSQL}
LABEL maintainer "${STACK_ADMIN_USERNAME} <${STACK_ADMIN_EMAIL}>"

ENV TZ=${STACK_TZ}
#RUN apt update;
#RUN apt install -y tzdata;
#ADD ./config-file.cnf /etc/mysql/conf.d/config-file.cnf

# ENV MYSQL_ALLOW_EMPTY_PASSWORD yes
# ENV MYSQL_ROOT_PASSWORD ${APPLICATION_DB_PASSWORD}
# ENV MYSQL_DATABASE ${APPLICATION_DB_DATABASE}
# ENV MYSQL_USER ${APPLICATION_DB_USER}
# ENV MYSQL_PASSWORD ${APPLICATION_DB_PASSWORD}