{
 "title": "System Monitoring",
 "tags": [ "alerts" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Load Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{alertname=\"high_load\", alertstate=\"firing\"}"
    }
   ]
  },
  {
   "title": "Service Down",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{alertname=\"service_down\", alertstate=\"firing\"}"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Free Swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Virtual Mem Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Free Memory (RAM + Swap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemFree + node_memory_SwapFree)/(node_memory_MemTotal + node_memory_SwapTotal)*100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail{mountpoint=\"/\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}