{
 "title": "Traefik full metrics",
 "description": "traefik all process",
 "tags": [
  "traefik",
  "load-balancer",
  "docker",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job:",
    "query": "label_values(process_start_time_seconds{service=\"traefik-ingress-service\"},job)"
   },
   {
    "name": "node",
    "label": "Node:",
    "query": "label_values(process_start_time_seconds{service=\"traefik-ingress-service\"}, instance)"
   },
   {
    "name": "backend",
    "label": "Service:",
    "query": "label_values(traefik_backend_requests_total,backend)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\",instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "404 Error Count last $interval",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{code=\"404\",method=\"GET\",backend=~\"$backend\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_backend_request_duration_seconds_sum{backend=~\"$backend\"}) / sum(traefik_entrypoint_requests_total{protocol=\"http\"}) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "$backend Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(traefik_backend_server_up{backend=~\"$backend\"})/count(traefik_config_reloads_total)"
    }
   ]
  },
  {
   "title": "$backend response time",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_backend_request_duration_seconds_sum{backend=~\"$backend\"}) / sum(traefik_backend_requests_total{backend=~\"$backend\"}) * 1000"
    }
   ]
  },
  {
   "title": "Total requests $backend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=~\"$backend\"}[$interval])) ",
     "legendFormat": "$backend"
    }
   ]
  },
  {
   "title": "Bad Status Code Count $interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{code=\"404\",method=\"GET\",backend=~\"$backend\"}[$interval])) by (backend)",
     "legendFormat": "{{backend}} "
    }
   ]
  },
  {
   "title": "Total requests over $interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total[$interval]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Used sockets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Access to backends",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{protocol=~\"http|https\",code=\"200\"}[$interval])) by (backend)",
     "legendFormat": "{{backend}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "ENTRYPOINT - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "BACKEND - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_backend_open_connections) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Status Code Count per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{backend=~\"$backend\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}