version: '3.9'

#ref
# https://grafana.com/docs/tempo/latest/configuration/
# https://grafana.com/docs/tempo/latest/configuration/#storage

networks:
  stack-nt:
    name: ${STACK_NETWORK_DEFAULT}
    external: true
  stack-nt-grf-loki:
    name: ${STACK_NETWORK_GRAFANA_LOKI}
    external: true


services:
  srv:
    image: ${STACK_SERVICE_IMAGE_URL}
    hostname: "${STACK_SERVICE_HOSTNAME}"
    volumes:
      - ${STACK_SERVICE_STORAGE_DATA_DIR}:/loki_data
      - ${STACK_INFRA_CONF_DIR}/grafana/loki/config.yml:/etc/loki/config.yml
      # - /var/run/docker.sock:/var/run/docker.sock
    command: 
      - -config.file=/etc/loki/config.yml
      - -print-config-stderr=true
    environment:
      TZ: ${STACK_TZ}
    # ports:
    #   - target: 3100
    #     protocol: tcp

    #   - target: 9095
    #     protocol: tcp
    deploy:
      mode: global
      placement:
        constraints:
          - ${APPLICATION_DEPLOY_NODE_TOOL}
      resources:
        limits:
          cpus: "${APPLICATION_DEPLOY_CPU}"
          memory: ${APPLICATION_DEPLOY_MEMORY}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
      labels:
        - traefik.docker.network=${STACK_NETWORK_DEFAULT}
        - traefik.http.routers.${STACK_SERVICE_NAME}.entryPoints=http,https
        - traefik.http.routers.${STACK_SERVICE_NAME}.tls=${STACK_TRAEFIK_TLS_ENABLED}
        - traefik.http.routers.${STACK_SERVICE_NAME}.rule=HostRegexp(`{subdomain:${STACK_SERVICE_HOSTNAME_PROXY}.*}`)
        - traefik.http.routers.${STACK_SERVICE_NAME}.service=${STACK_SERVICE_NAME}
        - traefik.http.services.${STACK_SERVICE_NAME}.loadbalancer.server.port=3100
    networks:
      - stack-nt
      - stack-nt-grf-loki

