version: '3.9'

#ref
# https://hub.docker.com/_/influxdb/
# https://docs.influxdata.com/influxdb/v2/install/upgrade/v1-to-v2/docker/

networks:
  stack-nt:
    name: ${STACK_NETWORK_DEFAULT}
    external: true

services:
  srv:
    image: ${STACK_SERVICE_IMAGE_URL}
    hostname: "${STACK_SERVICE_HOSTNAME}"
    volumes:
      - ${STACK_SERVICE_STORAGE_DATA_DIR}:/var/lib/influxdb2:rw
      #- ${STACK_INFRA_CONF_DIR}/influxdb/cert/cert.crt:/etc/ssl/influxdb-selfsigned.crt:rw
      #- ${STACK_INFRA_CONF_DIR}/influxdb/cert/cert.key:/etc/ssl/influxdb-selfsigned.key:rw
    command: 
      - --storage-wal-fsync-delay=1m
    environment:
      TZ: ${STACK_TZ}
      INFLUXDB_DB: ${STACK_SERVICE_DEFAULT_DATABASE}
      # INFLUXD_TLS_CERT: /etc/ssl/influxdb-selfsigned.crt
      # INFLUXD_TLS_KEY: /etc/ssl/influxdb-selfsigned.key

      # ref
      #   https://docs.influxdata.com/influxdb/v2/install/upgrade/v1-to-v2/docker/
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${STACK_SERVICE_DEFAULT_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${STACK_SERVICE_DEFAULT_PASS}
      DOCKER_INFLUXDB_INIT_ORG: ${STACK_PREFIX}
      DOCKER_INFLUXDB_INIT_BUCKET: ${STACK_SERVICE_DEFAULT_DATABASE}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${STACK_SERVICE_DEFAULT_TOKEN}
      DOCKER_INFLUXDB_INIT_RETENTION: 1w

    deploy:
      mode: global
      placement:
        constraints:
          - ${APPLICATION_DEPLOY_NODE_FW}
      resources:
        limits:
          cpus: "${APPLICATION_DEPLOY_CPU}"
          memory: ${APPLICATION_DEPLOY_MEMORY}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
      labels:
        - traefik.docker.network=${STACK_NETWORK_DEFAULT}
        - traefik.tcp.routers.${STACK_SERVICE_NAME}.rule=HostSNI(`*`)
        - traefik.tcp.routers.${STACK_SERVICE_NAME}.entryPoints=influxdb
        - traefik.tcp.routers.${STACK_SERVICE_NAME}.service=${STACK_SERVICE_NAME}
        - traefik.tcp.services.${STACK_SERVICE_NAME}.loadbalancer.server.port=8086
    networks:
      - stack-nt

