#-no-production
#ref
#   https://hub.docker.com/r/nowsci/samba-domain
version: '3.9'

networks:
  stack-nt:
    name: ${STACK_NETWORK_DEFAULT}
    external: true
  stack-nt-security:
    name: ${STACK_NETWORK_SECURITY}
    external: true

services:
  srv:
    image: ${STACK_SERVICE_IMAGE_URL}
    hostname: ${STACK_SERVICE_HOSTNAME}
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${STACK_TZ}
      DOMAIN: ${STACK_TARGET}.com
      DOMAINPASS: ${STACK_SERVICE_DEFAULT_PASS}
      # DNSFORWARDER: 192.168.3.1
      # HOSTIP: 192.168.3.222
    # volumes:
    #   - /data/docker/containers/samba/data/:/var/lib/samba
    #   - /data/docker/containers/samba/config/samba:/etc/samba/external
    # ports:
    #   - 53:53
    #   - 53:53/udp
    #   - 88:88
    #   - 88:88/udp
    #   - 135:135
    #   - 137-138:137-138/udp
    #   - 139:139
    #   - 389:389
    #   - 389:389/udp
    #   - 445:445
    #   - 464:464
    #   - 464:464/udp
    #   - 636:636
    #   - 1024-1044:1024-1044
    #   - 3268-3269:3268-3269
    dns_search:
      - corp.example.com
    deploy:
      mode: global
      placement:
        constraints:
          - ${APPLICATION_DEPLOY_NODE_TOOL}
      resources:
        limits:
          cpus: "${APPLICATION_DEPLOY_CPU}"
          memory: ${APPLICATION_DEPLOY_MEMORY}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    networks:
      - stack-nt-security