version: '3.9'

#ref
# https://github.com/prometheus/pushgateway
# https://github.com/PagerTree/prometheus-grafana-alertmanager-example/tree/master/prometheus
networks:
  stack-nt:
    name: ${STACK_NETWORK_DEFAULT}
    external: true

services:
  srv:
    image: ${STACK_SERVICE_IMAGE_URL}
    environment:
      TZ: ${STACK_TZ}

    command:
      - --web.enable-admin-api
    # ports:
    #   - target: 9091
    #     protocol: tcp
    #     mode: ingress
    deploy:
      mode: global
      placement:
        constraints:
          - ${APPLICATION_DEPLOY_NODE_TOOL}
      resources:
        limits:
          cpus: "${APPLICATION_DEPLOY_CPU}"
          memory: ${APPLICATION_DEPLOY_MEMORY}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    networks:
      - stack-nt
